---
title: "Structural controllability of regime shifts"
author: Juan Rocha
output:
  html_notebook:
    toc: yes
    toc_float: yes
    highlight: tango
    code_folding: hide
    df_print: paged
    theme: 
      bootswatch: cosmo
      code_font:
        google: Fira Code
editor_options: 
  chunk_output_type: inline
---

# Phase diagrams

```{r}
library(tidyverse)
library(deSolve)
library(waydown)
```

The equation:
$$\forall{i} \in\{1,...,n\}; \frac{dx_i}{dt} = u_i - s_ix_i + v_i \frac{x_{i}^{\alpha_{i}}}{z_i^{\alpha_{i}} + x_{i}^{\alpha_{i}}} 
- \sum_{j \neq i} A_{ij} (\delta_{ij}x_i - \delta_{ji}x_j)$$

```{r}
## parameters modified for one dimensional system:
n <- 1 # number of nodes
delta_ij <- 0.02 # no matrix, only one system
A_ij <- 1 # no matrix, only one system
u = rep(0.5, n)              # pollution load from humans
s = rep(2.2, n)              # internal loss rate (sedimentation)
v = rep(10, n)                # max level of internal nutrient release
z = 2.2       # threshold
alpha = 4                    # sharpness of the shift


## the model with diffusion:
##  + ((A_ij * delta_ij) %*% x) - (t(A_ij * delta_ij) %*% x)
dy <- function(x){ 
    (u - s*x + v * (x^alpha/(z^alpha + x^alpha))) + ((A_ij * delta_ij) %*% x) - (t(A_ij * delta_ij) %*% x)}

# values of x
xs <- seq(-2,7.5, by = 0.01)

# potential
Vs <- approxPot1D(dy, xs)

base::plot(xs,Vs, type = "l")
```

## Phase plot using PhaseR

```{r}
# This event function avoids negative levels of pollutants
# Add this directly above your call to ode()
posfun <- function(t, y, parms){
  with(as.list(y), {
    y[which(y<0)] <- 0
    return(y)
  })
}

## Pollution model:
pollution <- function(t, y, params){
  with(as.list(c(y, params)), {
    x = y
    pollutant <- u - s*x + v * (x^alpha/(z^alpha + x^alpha))
    outflow <-  (A_ij * delta_ij) %*% x
    inflow <-  t(A_ij * delta_ij) %*% x

    dy <- pollutant + (inflow - outflow)
    
    return(list(c(dy)))
  })
}

## set up flux matrix
n <- 1
delta_ij <- matrix(runif(n^2, min = 0.02, max = 0.05), ncol = n)
#delta_ij <- matrix(rep(0,n^2), ncol = n) # turn off difussion terms
diag(delta_ij) <- 0
A_ij <- 1#G[[1]] |> as_adjacency_matrix() |> as.matrix()
#diag(A_ij) <- 0
## Parameters: use rep() if the value is the same, or runif() ir meant to be different across systems
params <- list(
    u = rep(0.5, n),              # pollution load from humans
    s = rep(2.2, n),              # internal loss rate (sedimentation)
    v = rep(10, n),                # max level of internal nutrient release
    z = rep(2.2, n),        # threshold
    alpha = 4 ,                   # sharpness of the shift
    delta_ij = delta_ij,          # matrix of difussion terms
    A_ij = A_ij                   # adjacency matrix
)

## set up time steps
times <- seq(from = 0, to = 100, by = 0.01)

## initial conditions
yini <- rep(10,n) #runif(n, 5, 20)

## run the model
print(system.time(
    out <- ode(
      y = yini, times = times,  func = pollution, parms = params,
      method = "bdf" , ## see help("ode") for more methods
      events=list(func = posfun, time = times)
    )
))
```



```{r}
library(phaseR)
phase_plot <- function(pollution, params){
    flow <- flowField(
        pollution, xlim = c(0,7), ylim = c(0,7),
        parameters = params, system = "one.dim",
        points = 20, add = FALSE
    )
    nullcl <- nullclines(
        pollution, xlim = c(0,7), ylim = c(0,7),
        parameters = params, system = "one.dim",
        points = 500
    )
}

phase_plot(pollution, params)
```




