---
title: "Structural controllability and management of cascading regime shifts"
author: |
    | \small Juan Rocha^1,2,3^, Anne-Sophie Crépin^4^, César Hidalgo?
    | \small
    | \small ^1^Stockholm Resilience Centre, Stockholm University, Kräftriket 2B, 10691 Stockholm
    | \small ^2^Future Earth, The Swedish Royal Academy of Sciences, Lilla Frescativägen 4A, 104 05 Stockholm
    | \small ^3^South American Institute for Resilience and Sustainability Studies, Maldonado, Uruguay
    | \small ^4^Beijer Institute of Ecological Economics, The Royal Swedish Academy of Sciences
abstract: |

bibliography: refs.bib
csl: nature.csl
output:
  pdf_document:
    dev: pdf
    keep_tex: no
    toc: no
    latex_engine: xelatex
citecolor: blue
documentclass: article
font: Arial
fontsize: 10pt
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{dcolumn, rotating, longtable, lineno, float, fontspec, array, tabularx}
- \setmainfont{Arial}
- \linenumbers
- \renewcommand{\abstractname}{}
- \graphicspath{{figures/}}
- \usepackage[margin=2.5cm]{geometry}
editor_options:
  markdown:
    wrap: 72
---

```{r data, include=FALSE}
library(tidyverse)
library(here)

```

Outline:

1.  Intro [556/800w]

-   Regime shifts challenging for management
-   RS can be interconnected
-   How can we identify leverage points, or enough intervention points,
    to manage regime shifts?
-   Structural and dynamic controllability

2.  Methods [\>900/500w]

-   Data: CLDs RSDB
-   Models: pollution
-   resource systems
-   Control metrics

3.  Results [800w]
4.  Discussion [800w]
5.  Conclusion [300w]

# Introduction

Regime shifts are large, abrupt and persistent changes in the function
and structure of systems [@Anonymous:2004bq; @Scheffer:2001p2968]. They
have been documented in a variety of social-ecological systems
[@Scheffer:2009wl; @Biggs:2018hx], as well as climate [@Lenton:2019fv],
finance[@Guttal:2016kl], or health [@vandeLeemput:2014eb], to name a few
examples. Changes in structure and function of ecosystems can diminish
the benefits people get from nature such as food production, employment
opportunities, climate regulation, or water purification
[@Carpenter:2009jr]. For example, the North Atlantic cod collapse
represented X M of economic loss and compromised XX jobs. The weakening
or late arrival of the Indian summer monsoon can compromise food
production in one of the most densely populates regions of the world.
How management strategies avoid regime shifts or recover natural
ecosystems to desirable regimes are key research questions and an active
area of research [].

Regime shifts can be interconnected [@Rocha:2018gn]. The occurrence of
one can impact the likelihood of another through sequential tipping,
like a domino effect [@Wunderling:fj; @Rocha:2018gn]; or through two-way
interactions where new feedbacks can amplify or dampen the probability
of tipping over [@Rocha:2018gn]. Conceptual work have look at these
connections in the context of committed risk [@Steffen:2018ku;
@Lenton:2019fv], and recent modeling work has look at interactions
between climate tipping elements to understand additional challenges of
prediction [@Dekker:2010p5900], or the role of minimal network
configurations [@Wunderling:2020jk]. Besides climate, cascading effects
have also been studied in the context of engineered systems
[@Brummitt:2012it; @DSouza:2017hz], social and economic systems
[@Lee:2011p6824, @Brummitt:2017cg; @Anonymous:2015jy], or diseases
[@Watts:2005bq].

The possibility of cascading regime shifts rises a few additional
challenges for management. First, long distance coupling or
teleconnections [@Liu:2015go] between regime shifts implies that optimal
local or regional managerial practices might not be enough to reach
managerial objectives [@Rocha:2018gn; @Anonymous:2015du]. This not only
rises the governance issue of with whom does one need to coordinate for
successful management of local resources; it also implies a tragedy of
the commons with potential power asymmetries. Classical examples include
transnational resource systems where pollution or exploitation of a
resource in one side of the border impacts its quality on the other
side, or downstream (e.g. see Young for rivers, Keys for moisture
recycling). Second, and most importantly, connected regime shifts rises
the challenge of identifying sufficient and appropriate points of
intervention for managerial actions. On an interconnected world, how can
we identify leverage points to manage regime shifts? Are there regime
shifts -- or their interactions - that are harder to manage?

Here we answer these questions in the light of controllability of
complex systems. A system is controllable if one can drive it from any
initial state to any desired final state in finite time [@Kalman:1963bt;
@Liu:2015wl; @Liu:2011p6911]. Hence, controllability quantifies our
ability to steer dynamical systems [@Liu:2011p6911]. While control
theory has been fairly well developed in the realm of linear systems,
many open problems remain in the nonlinear one [@Cowan:2012fk;
@Liu:2015wl]. Strict global controllability for nonlinear systems has
been elusive, but weaker notions of controllability can be described
[@Liu:2015wl; @Zanudo:2017hw; @Mochizuki:2013uz]. For example, open loop
control has been used to steer chaotic systems to desired trajectories
in the phase space. Here we focus on feedback vertex sets as a proxy of
structural controllability [@Liu:2015wl; @Zanudo:2017hw] of regime
shifts and their interactions. We use network topology to gain insights
on the controllability of regime shift and the management challenges of
their cascading effects. We further test our intuitions with minimal
models of interconnected resources and pollution systems.

# Methods

We study structural controllability first on a static setting, and then
on minimal simulation experiments to approximate the dynamics of
interconnected systems. For the static setting we used causal diagrams
derived from the regime shifts database, an open online repository of
regime shift reviews [@Biggs:2018hx]. The database offers causal graphs
that summarize scientific hypotheses of how regime shifts work. Each
directed graph (N=30) can be interpreted as a network where a link
between two variables exist if a scientific paper has suggested a causal
link in the occurrence of the regime shift [@Biggs:2018hx]. We use these
networks to study structural controllability.

**Feedback control:** To steer a nonlinear system to a desired
attractor, one needs to find the feedback vertex set of the system. When
the system is described as a network, its state variables are
represented by nodes (or vertices), and the dependence between variables
as directed links (or arcs). A feedback in this context is a collection
of nodes and links that form a circular pathway. Feedbacks are often
responsible for the nonlinear dynamics of the system. If a network has
feedbacks, it is called a directed cyclic graph (DCG), and if it lacks
them a directed acyclic graph (DAG). The feedback vertex set is the set
of nodes that if deleted would render a DAG. The feedback arc set is the
set of links that if eliminated would render a DAG. Finding the feedback
vertex set or the arc set are equivalent problems [@Zhou:2016hu], yet
finding the minimum set is a nondeterministic polynomial-time hard
(NP-hard) problem. Once the system is reduced to a DAG, linear control
methods can be applied, such as finding unmatched nodes or the Kalman
rank condition for linear systems [@Liu:2015wl; @Liu:2011p6911]. Hence,
the set of nodes that need to be controlled to gain leverage on the
behaviour of a nonlinear system are the feedback vertex set plus the
unmatched nodes of the remaining linear system [@Zanudo:2017hw].

**Structural control on causal networks** We compute the proportion of
nodes that needs to be controlled for all causal networks from the
regime shifts database, as well as their pair-wise combinations. The
pair-wise combinations have been used to study plausible mechanisms that
can couple different types of regime shifts known as cascading effects
[@Rocha:2018gn]. We then can compare how structural controllability
change if ecological regime shifts are interconnected.

**Dynamic control on minimal models** To further test our intuitions, we
compared the results from structural controllability with modeling
experiments in simplified resource and pollutant models. We chose these
models because they are easier to parametrise that the qualitative
networks offered by the database, yet they encapsulate well understood
and common dynamics underlying many real world regime shifts. The
pollution system is defined by:

$$
\frac{dx_i}{dt} = u_i-s_ix_i+v_i \frac{x_i^{\alpha_i}}{z_i^{\alpha_i}+x_i^{\alpha_i}}- \sum_{j\not=i}(\delta_{ij}x_i-\delta_{ji}x_j)A_{ij}
$$

where $x_i$ is the level of pollutants of patch $i$ (e.g. a lake), $u_i$
denotes the level of pollutants from human activities, and $s_i$ the
internal loss rate (e.g. sedimentation). The term
$v_i \frac{x_i^{\alpha_i}}{z_i^{\alpha_i}+x_i^{\alpha_i}}$ is a
pollutant release nonlinear function where $v_i$ is the maximum level of
internal pollutants, $\alpha_i$ indicates the sharpness of the function,
and $z_i$ is a threshold level at which the system flips from low to
high nutrient regimes. Connectivity across patches is represented with
the term $\sum_{j\not=i}(\delta_{ij}x_i-\delta_{ji}x_j)A_{ij}$ where
$\delta_{ij}$ is the diffusion coefficient from patch $i \rightarrow j$,
given that $\delta_{ij}$ and $\delta_{ji}$ are not necessarily the same;
while $A_{ij}$ is the adjacency matrix. Similarly, the resource system
is defined by:

$$
\frac{dy_i}{dt} = r_iy_i\left(1-\frac{y_i}{k_i}\right)-c_i \frac{y_i^{\beta_i}}{q_i^{\beta_i}+y_i^{\beta_i}} + \sum_{j\not=i}(d_{ij}y_j-d_{ji}y_i)A_{ij}
$$

where $y_i$ is the state of the population $i$, $r_i$ is the intrinsic
growth rate, and $k_i$ its carrying capacity. The term
$c_i \frac{y_i^{\beta_i}}{q_i^{\beta_i}+y_i^{\beta_i}}$ is a Holling
type III predation function where $c_i$ represent refuges from predators
in patch $i$, $q_i$ is the half saturation biomass for predators (e.g. a
threshold for high to low abundance), and $\beta_i$ is the curvature
parameter that defines the abruptness of the shift [@Holling:2012fq].
The last term indicates mobility of the resource between patches at a
diffusion rate $d_{ij} \neq d_{ji}$, and an adjacency matrix $A_{ij}$
that takes 1 if patches $i$ and $j$ are connected, or zero otherwise.

Here we concentrate our efforts in exploring numerical simulations on
medium size interconnected systems ($N < 10^2$), with potentially
multiple feedbacks. Analytical solutions for the low dimensional
diffusion problem of our pollution and resource systems can be found in
[Crépin 2021]. The computer code used for our simulations as well as the
curated networks from the regime shifts database are available at:
<https://github.com/juanrocha/imperio>

# Results

# Discussion

# Conclusion

[400w]

# Acknowledgements

# References

::: {#refs}
:::

\pagebreak

# Supplementary Material {#sec:SM}

```{=tex}
\renewcommand\thefigure{S\arabic{figure}}
\renewcommand\thetable{S\arabic{table}}
\setcounter{table}{0}
\setcounter{figure}{0}
```
